# fly.toml app configuration file generated for cadet-interview-tracker on 2026-03-31T21:37:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cadet-interview-tracker'
primary_region = 'lhr'

[build]

[env]
  DB_PATH = '/data/cadet-interviews.db'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'cadet_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
